name: pandoc

on: 
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4.1.1 # checkout the repository content to github runner
        
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniconda-version: "latest"
          
      - name: Bash
        shell: bash -el {0}
        run: conda install -c conda-forge pandoc=2.19.2
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pandoc
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated quests" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
